# Exercise 1
## Authors: E. Vercesi; A. Dei Rossi, T. Marzi, M. Palomba

This Notebook is a guideline for Exercise 1

## Lists
Lists are one of the fundamental data structures in Python, used to store collections of items.

Give the following list (of fruits), learn how to
1. Acces elements (which is the index of the first element?)
2. Modify elements (e.g, change the third element to "pineapple")
3. Get the length
4. Add one element at the end
5. Remove one element (Take care of what returns and what happens to the original list. What is the meaning of in-place method?)
6. Learn about the meaning of slicing, then slice your list
7. Learn about the meaning of list comprehension and filter your list of fruits by keeping only fruits having an "a" inside

In [ ]:
fruits = ["apple", "banana", "cherry", "orange"]

## Numpy
NumPy is a fundamental Python library for numerical and scientific computing. It provides support for working with large, multi-dimensional arrays and matrices, as well as a collection of mathematical functions to operate on these arrays efficiently.
In this part, we will start learning some numpy basics

### Some exercises with numpy
Create random multidimensionals array and inspect their shape. Try different combinations of dimensions and different distributions (normal, uniform)

In [ ]:
import numpy as np # Import the package

Convert a Python list in a numpy array, and try to access the first element (which is the index of the first element?). What happens if you try the same procedure with a tuple? And what with a set?

In [ ]:
my_list = [1, 2, 3]
my_tuple = (1, 2, 3)
my_set = {1, 2, 3}

Given $v = [1, 2, 3]^T, w = [4, 5, 6]^T$ try to implement $v - w$, that is, element-wise subtraction. What happens if $v = [1, 2]^T$? And if $v = \begin{bmatrix} 4 & 5 \\ 7 & 8 \\ 6 & 9 \end{bmatrix}$? What should you do if you want to subtract $w$ to all the columns of $v$ in this last case?

A: If $v = [1, 2]^T$ then the substraction will get a dimensionality operation error. but if  $v = \begin{bmatrix} 4 & 5 \\ 7 & 8 \\ 6 & 9 \end{bmatrix}$ then $w$ will assume the same dimension as $v$ by repeating its rows/columns, process known as broadcasting.

In [ ]:
v = np.asarray([1, 2, 3])
w = np.asarray([4, 5, 6])
v = np.asarray([1, 2])
v = np.asarray([[4, 5], [7, 8], [6, 9]])

Given $v = [1, 2, 3]^T, \lambda = 3$ perform $\lambda v$. Be carefoul on the name you choose for the $\lambda$ variable in python and explain why "lambda" is not a good option

A: 'lambda' is a reserved keyword in python to define lambda functions.

In [ ]:
v = np.asarray([1, 2, 3])
lmbd = 4

Get the max of $v = [1, 2, 3]^T$

In [ ]:
v = np.asarray([1, 2, 3])
print('max: ' + str(v.max()))

max: 3


Learn and explain the differences between `np.dot`, `@`, `np.matmul` and `*`. Then, performs these operation matrices of different sizes. If you face some errors, try to explain why

A:
np.dot -> 1-D array is inner product, 2-D array is standart matrix multiplication, +2-D array sum over product of first array last axis to seconds array second to last axis.

np.matmul & @ -> these perform the same operation, stardart matrix multiplication

* -> element wise multiplication

In [ ]:
"""
v = np.arange(12).reshape((2,2,3))
t = np.arange(3)

print(v)
print(t)

print(np.dot(v,t))
"""


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[0 1 2]
[[ 5 14]
 [23 32]]


Learn how to define functions in Python. Then, define a function $f : x \mapsto \sqrt{x} + x^2 $ and apply it to every element of $v = [4, 9, 16]$. Note: this can be easly by only rely on `numpy` function. Learn also how to set some parameters as default values in functions and try to implement a version of this function that uses this features.

In [19]:
def f(x, with_square_root = True):
    a = np.power(x,2).astype(float)
    if with_square_root:
      a += np.sqrt(x)
    return a

v = np.asarray([4,9,16])
print(f(v))

[ 18.  84. 260.]


Reade the documentation of `np.arange` and `np.linspace`. Then, create 10 evenly spaced points in the interval $[0, 1]$ and $[0.5, 10]$ using both methods.

In [25]:
print(np.arange(0,1 + 1/10,(1 + 1/10)/10), end = '\n\n') # endpoint needs added step for closed interval
print(np.linspace(0,1,10), end = '\n\n')

[0.   0.11 0.22 0.33 0.44 0.55 0.66 0.77 0.88 0.99]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Learn about the meaning of slicing; then create a 4x4 matrix with random values between 1 and 10 and print: first row, first column, all the rows but the first, last column, the 2x2 core of the matrix

In [37]:
v = np.random.rand(4,4)*10 + 1
print(v, end = '\n\n')
print(v[1,:], end = '\n\n')
print(v[:,1], end = '\n\n')
print(v[1:], end = '\n\n') # np.delete(v,0,1)
print(v[:,-1], end = '\n\n')
print(v[1:3,1:3], end = '\n\n')

[[8.24396161 9.33108203 6.93886819 1.89766511]
 [5.9719603  5.54191468 6.27513753 5.99190122]
 [6.37881772 6.44151896 5.9341335  7.00055154]
 [3.98143925 1.94007236 6.38856218 6.55429496]]

[5.9719603  5.54191468 6.27513753 5.99190122]

[9.33108203 5.54191468 6.44151896 1.94007236]

[[5.9719603  5.54191468 6.27513753 5.99190122]
 [6.37881772 6.44151896 5.9341335  7.00055154]
 [3.98143925 1.94007236 6.38856218 6.55429496]]

[1.89766511 5.99190122 7.00055154 6.55429496]

[[5.54191468 6.27513753]
 [6.44151896 5.9341335 ]]



Create a random array of the size you prefere and print the maximum, the minimum and the sum. Try to create some multidimensional array to understand how to get e.g the maximum along different dimensions

In [30]:
v = np.random.rand(3,4,5)
print('max: '+str(np.max(v)))
print('min: '+str(np.min(v)))
print('sum: '+str(np.sum(v)))

max: 0.9976368786545468
min: 0.01175384592005091
sum: 28.260908924584008


Create a random array of integers dimensions $ 2 \times 4 \times 6$ and try to reshape it in varius way. If you face some errors, try to understand why. Learn also the documentation of funtions such as `np.newaxis` and `np.squeeze`: understand what they do and try them.

In [36]:
v = np.random.randint(10, size=(2,4,6))
#print(2*4*6)
v1 = v.reshape((2,2,12))
v2 = v.reshape((1,2,24))
v3 = np.squeeze(v2)

48
